version: 2
updates:

  # composer updates
  - package-ecosystem: "composer"
    directory: "/" # Location of package manifests
    target-branch: develop
    labels: bug
    schedule:
      interval: "daily"
